version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: robots-analyzer-app
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - db_data:/app/data
    networks:
      - robots_network

  nginx:
    image: nginx:alpine
    container_name: robots-analyzer-nginx
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - webapp
    networks:
      - robots_network

volumes:
  db_data:
    name: robots-analyzer-db

networks:
  robots_network:
    name: robots_network
    driver: bridge